roberta_base:
  model_name: deepset/roberta-base-squad2
  # model_name: roberta-base
  # model_name: xlm-roberta-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


bigbird:
  model_name: google/bigbird-roberta-large
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


roberta_large:
  model_name: roberta-large
  # model_name: xlm-roberta-large
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


roberta_large_squad:
  model_name: deepset/roberta-large-squad2
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


distilroberta:
  model_name: distilroberta-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


albert:
  model_name: albert-large-v2
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00003
  weight_decay: 1.0
  val_check_interval: 5
  eps: 0.000001
  betas: !!python/tuple [0.9, 0.999]
  kl_loss: True
  swa: True
  warmup: 100
  grad_clip_val: 1.0


funnel:
  model_name: funnel-transformer/large-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  eps: 0.0001
  betas: !!python/tuple [0.9, 0.999]
  kl_loss: True
  swa: True
  warmup: 100


bert_base:
  model_name: bert-base-uncased
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


bert_large:
  model_name: bert-large-cased
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


bert_large_wm:
  model_name: bert-large-cased-whole-word-masking
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


deberta_base:
  model_name: microsoft/deberta-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


deberta_large:
  model_name: microsoft/deberta-large
  gpus: 1
  batch_size: 12
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True

  
deberta_xlarge:
  model_name: microsoft/deberta-v2-xlarge
  gpus: 1
  plugins: ddp_sharded
  accelerator: ddp
  precision: 16
  batch_size: 10
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


bart_base:
  model_name: facebook/bart-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


bart_large:
  model_name: facebook/bart-large
  gpus: 1
  batch_size: 12
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


st_labse:
  model_name: sentence-transformers/LaBSE
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


# https://www.sbert.net/docs/pretrained_models.html
st_paraphrase:
  model_name: sentence-transformers/paraphrase-mpnet-base-v2
  gpus: 1
  batch_size: 32
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


sentence_bert:
  model_name: deepset/sentence_bert
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


gpt2:
  model_name: gpt2
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


electra:
  model_name: google/electra-large-discriminator
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00001
  warmup: 100
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: True
  swa: True


convbert:
  model_name: YituTech/conv-bert-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


ctrl:
  model_name: ctrl  # 6.5GB!!
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True