default_run:
  model_name: roberta-base
  gpus: 1
  batch_size: 16
  max_epochs: 4
  lr: 0.00001
  weight_decay: 1.0
  val_check_interval: 5
  gradient_clip_val: 0.5


large_run:
  model_name: roberta-large
  gpus: 1
  batch_size: 16
  max_epochs: 4
  lr: 0.00001
  weight_decay: 1.0
  val_check_interval: 5
  gradient_clip_val: 0.5