roberta_base:
  model_name: deepset/roberta-base-squad2
  gpus: [1]
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


bigbird:
  model_name: google/bigbird-roberta-large
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


roberta_large:
  model_name: deepset/roberta-large-squad2
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


distilroberta:
  model_name: distilroberta-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


albert:
  model_name: albert-large-v2
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00003
  weight_decay: 1.0
  val_check_interval: 5
  eps: 0.000001
  betas: !!python/tuple [0.9, 0.999]
  kl_loss: False
  swa: True
  warmup: 100
  grad_clip_val: 1.0


funnel:
  model_name: funnel-transformer/large-base
  gpus: [1]
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  eps: 0.0001
  betas: !!python/tuple [0.9, 0.999]
  kl_loss: False
  swa: True
  warmup: 100


bert_base:
  model_name: bert-base-uncased
  gpus: [1]
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


bert_large:
  model_name: bert-large-uncased
  gpus: [1]
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True

deberta_base:
  model_name: microsoft/deberta-base
  gpus: 1
  batch_size: 16
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


deberta_large:
  model_name: microsoft/deberta-large
  gpus: 1
  batch_size: 12
  max_epochs: 6
  lr: 0.00005
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


bart_base:
  model_name: facebook/bart-base
  gpus: [1]
  batch_size: 16
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True


bart_large:
  model_name: facebook/bart-large
  gpus: [1]
  batch_size: 12
  max_epochs: 6
  lr: 0.000025
  weight_decay: 1.0
  val_check_interval: 5
  kl_loss: False
  swa: True
